FROM ubuntu
WORKDIR /compnets
RUN apt-get update
RUN apt-get install -y net-tools netcat tcpdump inetutils-ping
    python-pip
CMD ["/bin/bash"]
CMD ["pip install -i https://test.pypi.org/simple/ Ass1"]
